
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
COMBO_ENABLE = yes
AUTO_SHIFT_ENABLE = no

SPACE_CADET_ENABLE = no
BOOTMAGIC_ENABLE = no
